{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aegis-statefulset.labels" . | nindent 4 }}
  annotations:
    # IRSA role ARN injected from Terraform output
    # eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT:role/aegis-statefulset
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
